8 swerve vision
DoF-6413/SummerSwerve2023 pull request #17
Opened 2023-08-17 02:43 UTC by alt09

have the pose estimator working  and logging values

2023-08-17 02:54 UTC, nancyesquivel10 reviewed
add these values in constants

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/drive/ModuleIOSparkMax.java
>          absoluteEncoderOffset = -267.6269 + 180;
please put this into a constant

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/drive/ModuleIOSparkMax.java
>          absoluteEncoderOffset = -269.7363 + 180;
same here constants

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/drive/ModuleIOSparkMax.java
>          absoluteEncoderOffset = -356.0449;
add to constants

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/drive/ModuleIOSparkMax.java
>          absoluteEncoderOffset = -177.6269;
add to constants

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/pose/Pose.java
> +                    16.4592,
put this field info in constants please

2023-08-17 02:54 UTC, nancyesquivel10 commented on src/main/java/frc/robot/subsystems/pose/Pose.java
> +                    8.2296);
put this field info in constants please

2023-08-19 20:51 UTC, nancyesquivel10 approved these changes, later dismissed
lgtm

2023-08-19 21:01 UTC, El1zabethS requested changes
Look at comments

2023-08-19 21:01 UTC, El1zabethS commented on src/main/java/frc/robot/Robot.java
> +  private VisionIOArduCam m_ArduCam;
Why are lines 32 and 33 there? Are they necessary? Remove if not.

2023-08-19 21:04 UTC, El1zabethS approved these changes

2023-08-19 21:05 UTC, nancyesquivel10 approved these changes

2023-08-19 21:06 UTC, merged